name: CI - Weather Monorepo

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Sincronizar workspace
        run: go work sync

      - name: Build apiclient
        run: cd apiclient && go build ./...

      - name: Build weather-app
        run: cd weather-app && go build ./...

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Sincronizar workspace
        run: go work sync

      - name: Instalar dependencias
        run: cd weather-app && go mod tidy

      - name: Correr tests
        run: cd weather-app && go test ./... -v

      - name: Cobertura
        run: |
          cd weather-app
          go test ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Build imagen Docker
        run: docker build -t weather-app .